import { z } from "zod";
import type { Timestamp } from "firebase-admin/firestore";

// ── Firestore document shape ──────────────────────────────────────────────────

export interface PatientSummaryDocument {
  userId: string;
  sessionId?: string;
  /** Short human-readable title, e.g. "Patient Summary – Jan 2026" */
  title: string;
  /** Comprehensive narrative paragraph generated by the AI */
  narrative: string;
  /** Chief complaints / presenting symptoms */
  chiefComplaints: string[];
  /** Active diagnoses with optional ICD-10 codes */
  diagnoses: Array<{ name: string; icd10?: string; status: string }>;
  /** Current medications */
  medications: Array<{ name: string; dosage?: string; frequency?: string }>;
  /** Vital signs captured in the session */
  vitals: Array<{ name: string; value: string; unit?: string }>;
  /** Known allergies */
  allergies: string[];
  /** Risk factors identified */
  riskFactors: string[];
  /** Clinical recommendations */
  recommendations: string[];
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

// ── DTO — outbound ────────────────────────────────────────────────────────────

export interface PatientSummaryDto {
  id: string;
  userId: string;
  sessionId?: string;
  title: string;
  narrative: string;
  chiefComplaints: string[];
  diagnoses: Array<{ name: string; icd10?: string; status: string }>;
  medications: Array<{ name: string; dosage?: string; frequency?: string }>;
  vitals: Array<{ name: string; value: string; unit?: string }>;
  allergies: string[];
  riskFactors: string[];
  recommendations: string[];
  createdAt: string; // ISO-8601
  updatedAt: string; // ISO-8601
}

// ── Mapper ────────────────────────────────────────────────────────────────────

export function toPatientSummaryDto(
  id: string,
  doc: PatientSummaryDocument,
): PatientSummaryDto {
  return {
    id,
    userId: doc.userId,
    sessionId: doc.sessionId,
    title: doc.title,
    narrative: doc.narrative,
    chiefComplaints: doc.chiefComplaints,
    diagnoses: doc.diagnoses,
    medications: doc.medications,
    vitals: doc.vitals,
    allergies: doc.allergies,
    riskFactors: doc.riskFactors,
    recommendations: doc.recommendations,
    createdAt: doc.createdAt.toDate().toISOString(),
    updatedAt: doc.updatedAt.toDate().toISOString(),
  };
}

// ── DTO — inbound (create) ────────────────────────────────────────────────────

export const CreatePatientSummarySchema = z.object({
  userId: z.string().min(1, { message: "userId is required" }),
  sessionId: z.string().optional(),
  title: z.string().min(1),
  narrative: z.string().min(1),
  chiefComplaints: z.array(z.string()).default([]),
  diagnoses: z
    .array(
      z.object({
        name: z.string(),
        icd10: z.string().optional(),
        status: z.string(),
      }),
    )
    .default([]),
  medications: z
    .array(
      z.object({
        name: z.string(),
        dosage: z.string().optional(),
        frequency: z.string().optional(),
      }),
    )
    .default([]),
  vitals: z
    .array(
      z.object({
        name: z.string(),
        value: z.string(),
        unit: z.string().optional(),
      }),
    )
    .default([]),
  allergies: z.array(z.string()).default([]),
  riskFactors: z.array(z.string()).default([]),
  recommendations: z.array(z.string()).default([]),
});

export type CreatePatientSummaryInput = z.infer<
  typeof CreatePatientSummarySchema
>;

// ── DTO — inbound (list) ──────────────────────────────────────────────────────

export const ListPatientSummariesSchema = z.object({
  userId: z.string().min(1, { message: "userId is required" }),
  limit: z.number().int().min(1).max(100).optional().default(20),
});

export type ListPatientSummariesInput = z.infer<
  typeof ListPatientSummariesSchema
>;

// ── DTO — inbound (delete) ────────────────────────────────────────────────────

export const DeletePatientSummarySchema = z.object({
  userId: z.string().min(1),
  summaryId: z.string().min(1),
});

export type DeletePatientSummaryInput = z.infer<
  typeof DeletePatientSummarySchema
>;
