import { WithContext, ApiError } from "@/lib/api/with-context";
import { GetThumbnailUrlUseCase } from "@/data/files";

// GET /api/files/[fileId]/thumbnail — redirect to a signed thumbnail URL
// Thumbnails are generated by the Firebase Cloud Function (Firestore document trigger).
export const GET = WithContext<{ fileId: string }>(
  async ({ user, profileId }, { fileId }) => {
    const url = await new GetThumbnailUrlUseCase().execute({
      userId: user.uid,
      profileId,
      fileId,
    });
    if (!url) throw ApiError.notFound("Thumbnail not found.");

    return new Response(null, {
      status: 302,
      headers: {
        Location: url,
        "Cache-Control": "private, max-age=3600, stale-while-revalidate=600",
      },
    });
  },
);
