/**
 * Diet Planner Chat Agent — 7-day meal plan generation via chat
 *
 * Handles the `dietPlanner` routing decision from the Gateway Agent.
 * When a patient explicitly requests a diet or meal plan, the Gateway routes
 * to this agent instead of the general Clinical Agent.
 *
 * Built via `createAgent` which provides:
 * - Credit gating (one credit per call)
 * - RAG retrieval (patient conditions, vitals, allergies, preferences — reranked)
 * - Clinical guideline injection (ADA 2026, NICE, AHA)
 * - ToolLoopAgent delegation (Gemini Pro + thinking mode, up to 15 steps for 7 days)
 * - Google context caching for static prompt + tools
 *
 * The 7-day plan is generated by the model calling `submitDailyPlan` 7 times.
 * Patient personalisation (biometrics, conditions, allergies) comes from RAG.
 * Regional adaptation (cuisine, ingredients, SOPs) comes from buildDynamicContext.
 */

import type { InferAgentUIMessage } from "ai";
import { createAgent } from "../base/agent";
import { buildDietPlannerPrompt } from "./prompt";
import { buildDietDynamicContext } from "./context";
import { createSubmitDailyPlanTool } from "./tools/submit-diet-day.tool";
import type { EnhancedDietDay } from "./tools/submit-diet-day.tool";

export type { EnhancedDietDay };

/** Singleton — import this throughout the server-side application. */
export const dietPlannerChatAgent = createAgent({
  id: "diet-planner",
  buildSystemPrompt: () => buildDietPlannerPrompt(),
  buildDynamicContext: (options) => buildDietDynamicContext(options),
  maxSteps: 15,
  buildTools: () => {
    // Fresh collector array each request — the closure captures it.
    const collectedDays: EnhancedDietDay[] = [];
    return {
      submitDailyPlan: createSubmitDailyPlanTool(collectedDays),
    };
  },
});

/** Typed UIMessage for the diet planner agent — use on client for typed tool parts. */
export type DietPlannerAgentUIMessage = InferAgentUIMessage<
  typeof dietPlannerChatAgent
>;
