/**
 * Memory Tool — Save and recall facts about the patient across sessions.
 *
 * Gives the agent persistent cross-session memory stored in Firestore.
 * The agent decides what facts are worth remembering (medical conditions,
 * allergies, preferences, lifestyle info) and can recall them later.
 *
 * Storage: `profiles/{profileId}/memories/{memoryId}`
 */

import { tool, zodSchema } from "ai";
import { z } from "zod";
import { memoryRepository } from "@/data/memory/repositories/memory.repository";
import type { MemoryCategory } from "@/data/memory/models/memory.model";

const CATEGORY_OPTIONS = [
  "medical",
  "preference",
  "lifestyle",
  "allergy",
  "summary",
] as const;

// ── Action handlers ───────────────────────────────────────────────────────────

async function handleSave(
  userId: string,
  profileId: string,
  sessionId: string,
  input: { category: string; content: string },
) {
  const memory = await memoryRepository.save(userId, profileId, {
    category: input.category as MemoryCategory,
    content: input.content,
    sessionId,
  });
  return {
    saved: true,
    id: memory.id,
    message: `Remembered: "${memory.content}"`,
  };
}

function formatRecallResult(
  memories: Awaited<ReturnType<typeof memoryRepository.list>>,
) {
  return {
    found: true,
    count: memories.length,
    memories: memories.map((m) => ({
      id: m.id,
      category: m.category,
      content: m.content,
      createdAt: m.createdAt,
    })),
  };
}

async function handleRecall(profileId: string, category?: string) {
  const memories = await memoryRepository.list(
    profileId,
    30,
    category as MemoryCategory | undefined,
  );
  if (memories.length === 0) {
    return {
      found: false,
      count: 0,
      message: "No memories saved for this patient yet.",
    };
  }
  memoryRepository
    .touchAccessed(
      profileId,
      memories.map((m) => m.id),
    )
    .catch((err) =>
      console.error("[memoryTool] Failed to touch accessed:", err),
    );
  return formatRecallResult(memories);
}

async function handleDelete(profileId: string, memoryId: string) {
  await memoryRepository.delete(profileId, memoryId);
  return { deleted: true, message: "Memory deleted." };
}

// ── Schema ────────────────────────────────────────────────────────────────────
// Flat object instead of discriminatedUnion — Google's cached_content API
// rejects JSON Schema `const` (generated by z.literal inside oneOf).

const memoryInputSchema = zodSchema(
  z.object({
    action: z
      .enum(["save", "recall", "delete"])
      .describe("Action to perform: save, recall, or delete"),
    category: z
      .enum(CATEGORY_OPTIONS)
      .optional()
      .describe(
        "Category of fact (required for save, optional filter for recall)",
      ),
    content: z
      .string()
      .max(500)
      .optional()
      .describe("Concise fact to remember (required for save)"),
    memoryId: z
      .string()
      .optional()
      .describe("ID of the memory to delete (required for delete)"),
  }),
);

const TOOL_DESCRIPTION =
  "Use this tool to read and maintain long-term patient memory.\n\n" +
  "Rules:\n" +
  "- If the patient's message might depend on medical history, allergies, preferences, or past conditions, recall first, then reply.\n" +
  "- If the message is fully self-contained or general knowledge, reply directly without recalling.\n" +
  "- Save durable patient facts: diagnosed conditions, allergies, current medications, lifestyle habits, dietary preferences or restrictions.\n" +
  "- Do NOT save transient conversation details, greetings, or generic medical advice.\n" +
  "- Keep each saved fact concise (one sentence).\n" +
  "- Keep memory operations invisible in user-facing replies.";

// ── Tool factory ──────────────────────────────────────────────────────────────

export function createMemoryTool(
  userId: string,
  profileId: string,
  sessionId: string,
) {
  return tool({
    description: TOOL_DESCRIPTION,
    inputSchema: memoryInputSchema,
    execute: async (input) => {
      switch (input.action) {
        case "save":
          return handleSave(userId, profileId, sessionId, {
            category: input.category ?? "medical",
            content: input.content ?? "",
          });
        case "recall":
          return handleRecall(profileId, input.category);
        case "delete":
          return handleDelete(profileId, input.memoryId ?? "");
      }
    },
  });
}
